backend:
  name: git-gateway
  branch: main

media_folder: 'content/images'
public_folder: '/images'

collections:
  - name: 'blog'
    label: 'Posts'
    folder: 'content'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Datum', name: 'date', widget: 'datetime' }
      - { label: 'Categorie', name: 'category', widget: 'string' }
      - { label: 'Inhoud', name: 'body', widget: 'markdown' }
