backend:
  name: git-gateway
  repo: kapitalisman/bergkam
  branch: main
  identity_url: https://auth.decapbridge.com/sites/f6fb4069-235a-413c-96c5-8d90653fe2bf
  gateway_url: https://gateway.decapbridge.com

logo_url: https://decapbridge.com/decapcms-with-bridge.svg
site_url: https://bergkam.nl

media_folder: 'content/images'
public_folder: '/images'

collections:
  - name: 'blog'
    label: 'Posts'
    folder: 'content'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Datum', name: 'date', widget: 'datetime' }
      - { label: 'Categorie', name: 'category', widget: 'string' }
      - { label: 'Inhoud', name: 'body', widget: 'markdown' }
