backend:
  name: git-gateway
  repo: kapitalisman/bergkam
  branch: main
  identity_url: https://auth.decapbridge.com/sites/f6fb4069-235a-413c-96c5-8d90653fe2bf
  gateway_url: https://gateway.decapbridge.com

logo:
  src: https://decapbridge.com/decapcms-with-bridge.svg
  show_in_header: true

site_url: https://bergkam.nl

media_folder: 'content/images'
public_folder: '/images'

collections:
  - name: 'posts'
    label: 'Posts'
    label_singular: 'post'
    description: 'Blog articles'
    folder: 'content'
    create: true
    extension: 'md'
    format: 'yaml-frontmatter'
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
        }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
